workflows:
  ios-workflow:
   name: iOS Workflow
#    scripts:
#        - name: Flutter build ipa and automatic versioning
#          script: |
#            flutter build ipa 
   artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
   publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true     # To receive a notification when a build succeeds
          failure: false    # To not recei
#       app_store_connect:
#         apple_id: $APPLE_ID_EMAIL
#         password: $APP_SPECIFIC_PASSWORD
